# Generated by Django 4.0.2 on 2022-02-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_actorage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorAge',
            new_name='ActorName',
        ),
    ]
